// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using masterdata_api.Data;

#nullable disable

namespace masterdata_api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204182007_AddSiteEntity")]
    partial class AddSiteEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("masterdataapi.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SfEjendomsNr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SfEjendomsNr");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("masterdataapi.Models.WindTurbine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastralDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CadastralNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CapacityKw")
                        .HasColumnType("integer");

                    b.Property<string>("CoordinateOrigin")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("CoordinateX")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("CoordinateY")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DecommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gsrn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("HubHeightM")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LocalAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("OriginalConnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("RotorDiameterM")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeDesignation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Gsrn")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("WindTurbines");
                });

            modelBuilder.Entity("masterdataapi.Models.WindTurbine", b =>
                {
                    b.HasOne("masterdataapi.Models.Site", "Site")
                        .WithMany("WindTurbines")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("masterdataapi.Models.Site", b =>
                {
                    b.Navigation("WindTurbines");
                });
#pragma warning restore 612, 618
        }
    }
}
